### ISSUE TITLE
chronological order of scheduling

### ISSUE THREAD

**Issue by JunioCalu** [ErsatzTV/ErsatzTV#1345]
when video files are not explicitly named like "s1e1.mp4" "s1e2.mp4", "s1e3.mp4" then how is the chronological order defined in the schedule?

**Comment by jasongdove** [comment]
Chronological ordering uses release dates primarily, and falls back to season, then episode to resolve a conflict with release dates. From media servers, all episodes should have release dates, otherwise NFO metadata can be used with local libraries. See https://ersatztv.org/user-guide/local-libraries/#episode-nfo-metadata

**Comment by JunioCalu** [comment]
When the media is of type "Other Videos", and does not contain "NFO metadata" files and the file names do not follow a sequence, is any order defined? by the file creation date, for example ?
