### ISSUE TITLE
Intelligently schedule movies

### ISSUE THREAD

**Issue by liam8888999** [ErsatzTV/ErsatzTV#1356]
Eg movie 1 should be scheduled before movie 2. I can only see this working if the movies have the same name and a clear number though

**Comment by WallaWallaWA** [comment]
You can create a collection that is ordered so that you can set which movie plays first, second, and so on. So instead of release date order, for collections like Star Wars, you can use the 'machette order'; for the MCU, you can use chronological order, etc. 
Is this what you're wanting to do?

**Comment by WallaWallaWA** [comment]
Here's a screenshot:
[Custom playback order](https://i.imgur.com/pg0bCWT.png)

**Comment by liam8888999** [comment]
That is pretty much what I was wanting to do but with the amount of movies I have it would take a long time so it would be good if it could auto schedule movie 1,movie 2 and movie 3 as essentially 1 movie

**Comment by WallaWallaWA** [comment]
Maybe I'm not understanding. If you're wanting to schedule all your movies together, which is what it somewhat sounds like, I'm not sure that you're really getting the most benefit from ErastzTV. Perhaps you could provide a bit more detail or information on what you want to achieve, including one or more examples; with more to work with, it's possible that I or someone else can provide more direction on a solution.

If you want to schedule a number of movie series or theme movies together, than a collection with custom playback order will work. I have a 'Trilogies and More' channel with various movie series (Back to the Future, Godfather, Rocky, MIB, etc.) that, for now, has 230 movies in that collection which plays each series in order. It does take a little time to set up, but once done, maintenance (i.e., a new series addition) takes just a few seconds. For other series (Star Wars, MCU, Sherlock Holmes, James Bond, Star Trek, etc.) they each have their own separate channel.

You can also create multi-collections that are a collection of other collections, both regular collections and/or smart collections, to help group items together, so that might be something to look into.
