### ISSUE TITLE
"Multiple" playout mode isn't working for me

### ISSUE THREAD

**Issue by fmr-iv** [ErsatzTV/ErsatzTV#1359]
I've set up a Collection of Nickelodeon shows:

![image](https://github.com/jasongdove/ErsatzTV/assets/4317891/778e9b5f-c856-48ee-a7be-de86cd10ce23)

I created my Schedule with the "Multiple" option enabled and set to 2:

![image](https://github.com/jasongdove/ErsatzTV/assets/4317891/6a9cd43e-b17c-4ab3-8a2d-665358ba5a08)

But the Playout is only playing 1 episode of each show before moving to a new one. The XML seems to be the same:

![image](https://github.com/jasongdove/ErsatzTV/assets/4317891/90b33814-55b9-49ad-b70c-cae50699feaa)

![image](https://github.com/jasongdove/ErsatzTV/assets/4317891/0e2aa174-4d5c-4915-be33-4173b95d0e9e)

**Comment by jasongdove** [comment]
The playout modes are described here https://ersatztv.org/docs/user-guide/create-channels#schedule-items

> Multiple: Play the specified Multiple Count of media items from the collection before advancing to the next schedule item.

In this case, your collection "Nickelodeon" has multiple shows that are all shuffled together, and ETV will play 2 items from that shuffle before advancing to the next schedule item. Since there is only one schedule item, it is effectively the same as flood.

I think you're touching on a scheduling scenario that is not yet supported very well. The current way to achieve what you're looking for is to create a schedule item for each show, configured as chronological and multiple 2 (or whatever is appropriate for that show). You can then edit the schedule itself to shuffle schedule items (meaning it would randomize the order of shows). This is done in the same place that you would edit the schedule name.

With that configuration, the order of shows would be shuffled, and each show would play its configured number of episodes in chronological order before advancing to the next (randomly-selected) show.

**Comment by jasongdove** [comment]
@fmr-iv the latest develop release has a new feature `Fill With Group Mode` that I think will be closer to your expectations.

**Comment by jasongdove** [comment]
See #1534
