### ISSUE TITLE
Ability to let ffmpeg decide number of threads

### ISSUE THREAD

**Issue by RankWeis** [ErsatzTV/ErsatzTV#1387]
ffmpeg by default will try to find an optimal number of threads to use (according to https://superuser.com/a/726379). An easy option here would maybe be to return an empty list when threads is set to 0 - https://github.com/ErsatzTV/ErsatzTV/blob/main/ErsatzTV.FFmpeg/Option/ThreadCountOption.cs

It's unclear to me why, but currently when I set threads to 0 via the interface, it gets defaulted to 1.

Use case is I'm unclear with hardware encoding how many threads to give ffmpeg, and whether those threads are all CPU based. Letting the tool handle it for me would be nice.

**Comment by jasongdove** [comment]
You are letting the tool handle it for you (ErsatzTV) ;-)

ETV will allow an automatic/custom thread count in all scenarios except when:

1. Realtime output is used with stream seek
https://github.com/ErsatzTV/ErsatzTV/blob/b038a58fa24bdae0424f07b069c415af0ac14423/ErsatzTV.FFmpeg/Pipeline/PipelineBuilderBase.cs#L628-L635
3. Hardware acceleration is used
https://github.com/ErsatzTV/ErsatzTV/blob/b038a58fa24bdae0424f07b069c415af0ac14423/ErsatzTV.FFmpeg/Pipeline/PipelineBuilderBase.cs#L619-L627

This is to avoid

1. Bugs in ffmpeg that effectively completely prevent streaming
2. Incompatibility with hardware-accelerated decoders and filters that only support a single thread

I have gone back and forth on this a couple times, but have decided against allowing problematic/incompatible configurations that increase support requests due to transcoding errors.

**Comment by RankWeis** [comment]
awesome! Thanks for the response
