### ISSUE TITLE
[Feature Request] Setting to transcode only audio (copy video)

### ISSUE THREAD

**Issue by RandomGithubUsername** [ErsatzTV/ErsatzTV#1626]
I use Tivimate as client which perfectly plays even high bitrate Bluray remuxes that I have BUT it doesn't support DTS/DTSHD-MA/TruHD audio formats. Is there a way to create channels that will only transcode audio and leave video as-is? I tinkered a lot with FFMPEG profiles and none of the settings were satisfactory - either the video starts slow and/or too much buffering and/or pixellated (low quality). Ideally HLS-Direct with just audio being transcoded option would be great.

**Comment by wdstudios2** [comment]
Unfortunately, HLS-Direct isn't an actual standard that exists anywhere outside of ETV, and it isn't intended to work with anything. If it does work with anything, it's by miracle rather than by design.

Current industry standards basically assume only two use cases for streaming video: the pre-encoded kind that you can start, stop, and rewind willy-nilly (like Youtube and Netflix), and livestreaming, which needs to be encoded on-the-fly. Nobody ever anticipated that we'd want to take pre-encoded stuff and pretend it's a live broadcast.

Don't blame Jason; blame industry standards.
