### ISSUE TITLE
Alternate schedule times can't be saved unless they're in the top row

### ISSUE THREAD

**Issue by andrewjsim** [ErsatzTV/ErsatzTV#1628]
Version: v0.8.4-beta-win-x64

I'm trying to set up a channel with two schedules, one for Sun-Thu and one for Fri and Sat. I create the second schedule in my channel's alternate schedules page, but only the top row will save the custom days/months, with the lower rows reverting to \*any\* after I click "Save Changes" and check again. If the rows are reordered, the new top one will be allowed to be saved but the new lower ones will be wiped back to \*any\*.

Interestingly and possibly relatedly, if there's only one row, it also can't be saved and reverts to \*any\*, but that's more intuitive to me since if there's only one schedule it should be playing all the time!

**Comment by jasongdove** [comment]
This is by design - the list is prioritized from top to bottom, so the bottom row will always match all days, ensuring each day of the year will have a schedule. You can just pick one to assign to specific days in the top row, and leave the other one matching everything in the bottom.

ETV checks from top to bottom and uses the first row that matches the day that it needs to schedule.

**Comment by andrewjsim** [comment]
Thank you for explaining that! So it seems like my use case should be:

```
Line 1: Fri, Sat
Line 2: All days
```

Where Friday and Saturday would match on the first line and thus never "fall through" to the second, catch-all line.
