### ISSUE TITLE
Cannot play newer content, error parsing global option

### ISSUE THREAD

**Issue by Andrewpaps** [ErsatzTV/ErsatzTV#1713]
Running into this issue on playback.

![image](https://github.com/ErsatzTV/ErsatzTV/assets/71562383/dd0ec810-0f6c-4efd-86b7-b344a0191d99)

Regular perhaps less demanding TV Series seem to be playing correctly, but larger new release films are throwing this error.

**Comment by jasongdove** [comment]
HDR content is currently only supported using `HLS Direct` streaming mode. For other updates, see https://github.com/ErsatzTV/ErsatzTV/issues/1297

**Comment by jasongdove** [comment]
To be clear, this is a duplicate of #1297 - and it is planned to support HDR to SDR transcoding.

**Comment by Andrewpaps** [comment]
Already tried HLS Direct and this behavior is absolutely still occurring regardless of selected streaming mode including HLS Direct, even after restarting ErstatzTV as well as clients.

**Comment by jasongdove** [comment]
Which client are you using? If Plex, it only supports MPEG-TS and ignores the streaming mode setting. Other clients need to refresh the M3U to use the newly configured streaming mode.

**Comment by Andrewpaps** [comment]
Appears to be happening on both Jellyfin and TiviMate after deleting and re-adding. Adding as a HDHomeRun in Jellyfin will display SDR content but adding the M3U link just encounters an error.

**Comment by dsync89** [comment]
+1 for this and definitely looking for the day this HDR->SDR arrived so I don't have to chance if it is a HDR movie playing on a channel right now and render this error. Usually I have to quit Kodi entirely instead of waiting it to timeout and remember NOT to switch back to that channel.  

Jellyfin seems to have HDR->SDR tonemapping done right in their ffmpeg build. Not sure how they built it but I think the `ffmpeg` in jellyfin work. Too bad it's dynamically link so there is no way to test it on ErsatzTV container
