### ISSUE TITLE
Schedule skips an episode or two

### ISSUE THREAD

**Issue by nothing2obvi** [ErsatzTV/ErsatzTV#1957]
A minor bug. Using it on Mac. When I create a new schedule, it conveniently leaves out S01E01, sometimes S01E02. I'm using Jellyfin as library source and performed a deep scan of my TV shows.

![Screenshot 2024-12-11 at 12 38 28 PM](https://github.com/user-attachments/assets/c2a21dda-ac0a-419d-ba6f-fd447b596c92)

**Comment by jasongdove** [comment]
With the default scheduling mode (flood scheduling, as opposed to block scheduling) playouts start at midnight of the current day, so the later in the day that you reset the playout, the more episodes will be "skipped" (scheduled before "now").

If that's not the issue you'll have to give some details about your media items (do all those episodes exists in etv) and your specific schedule since there are so many ways to configure things - a list of the resulting episodes gives extremely little to go on.

**Comment by nothing2obvi** [comment]
I see I think it was what you said because I changed the time the schedule starts then reset the playout and now it's all good. Thanks!
