### ISSUE TITLE
stable-nvidia uses cpu instead of nvenc

### ISSUE THREAD

**Issue by krutburken** [ErsatzTV/ErsatzTV#206]
This is probably more of a support request, but I can't get ersatztv to use nvenc. I've tried latest-nvidia and develop-nvidia but both use the cpu instead. Nvenc works with Jellyfin on the same machine though. I there anything obvious I missed? Docs (https://ersatztv.org/user-guide/install/) doesn't say anything specific other than which image to use

top:
![top](https://user-images.githubusercontent.com/13684929/119393422-d2bcc600-bcc8-11eb-908f-61dde1b68b81.JPG)

nvidia-smi:
![nvidia-smi](https://user-images.githubusercontent.com/13684929/119393446-d94b3d80-bcc8-11eb-9443-24326ce5f55f.JPG)

**Comment by jasongdove** [comment]
Thanks for identifying this documentation gap. See the nvidia docker-compose overrides for required settings https://github.com/jasongdove/ErsatzTV/blob/main/docker/docker-compose.nvidia.yml

**Comment by krutburken** [comment]
Hey, thanks for the quick reply. Unfortunately it still doesn't use nvenc after testing with this docker-compose. What is the docker-cli equivalent of this btw? (I normally don't use docker-compose)

**Comment by jasongdove** [comment]
There is also a hardware acceleration drop down that needs to be set along with the video codec in the FFmpeg Profile used on the channel. Have you selected `Nvenc` in the drop down, and tried a codec like `h264_nvenc` or `hevc_nvenc`?

**Comment by krutburken** [comment]
Oh wow, I had completely missed that. Works perfectly after enabling nvenc in the ffmpeg profile, and the setting from the docker-compose wasn't necessary either. Thanks for the help!

**Comment by Toylerrr** [comment]
Hello Im currently having the same problem but within the video formats h264_nvenc is not available 
![image](https://user-images.githubusercontent.com/4400902/198098339-aed9a543-34ec-4b86-bc33-281776c61e14.png)

**Comment by jasongdove** [comment]
This issue was from before the ffmpeg profile settings were redesigned. It will now auto-select an appropriate encoder using a few data points:

1. `Hardware Acceleration` setting
2. `Video Format` setting
3. Detected video card capabilities

If you have `Hardware Acceleration` set to `Nvenc` and Video Format set to `h264` it will use `h264_nvenc` if your video card is properly passed through (only applies to docker), and it supports that encoder. Otherwise it will fall back to the software encoder `libx264`.
