### ISSUE TITLE
`Shuffle Schedule Items` is missing documentation

### ISSUE THREAD

**Issue by keggster101020** [ErsatzTV/ErsatzTV#825]
When using the schedules UI there is a drift between the options available in the documentation and what is actually there.

For example:

### Missing Fixed Start Type
![image](https://user-images.githubusercontent.com/7826898/170892000-91995590-f9ad-45ec-9d25-30903cd8f368.png)

### Missing Flood Playout Mode
![image](https://user-images.githubusercontent.com/7826898/170892022-a49dc841-3eb6-41ec-94ff-957d7adefb2f.png)

--------------------

Using latest image version 0.5.8-beta-docker

----------------------

**Comment by jasongdove** [comment]
You are correct that the documentation is lacking here, will address.

What's happening is that you have `Shuffle Schedule Items` enabled on the schedule, and the missing options are expected to be missing in this case because they are incompatible with that option. If you disable `Shuffle Schedule Items` you will be able to pick fixed start times, reorder schedule items and flood schedule items again.
