### ISSUE TITLE
[Feature Request] Generated Up Next Filler and Caption

### ISSUE THREAD

**Issue by Long-Man** [ErsatzTV/ErsatzTV#978]
**Filler**
Something similar to what is done for music  and use subtitles to show the next 5 items and the times. It could also be use as a tail filler for the time that there no item to fill. 

**Watermark**
Plays the 

- "Currently On" or whatever about 10 seconds into you tuning in or start of a new item
- "Coming Up" about 30 sec to 1 min at end

**Comment by Long-Man** [comment]
If possible generate the background from the channel logo

**Comment by Hello-World-Traveler** [comment]
@jasongdove hi there, is this possible?  instead of the media play from one to the next. it slows a up next screen for a few seconds before playing the next media?

Something like this on the left hand side and on the right, what is coming up next maybe with a count down timer?
![Image](https://github.com/user-attachments/assets/016a46c7-4f7e-46ec-a67f-5eb45fd566e2)
